apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policy-read-view-binding
subjects:
  - kind: ServiceAccount
    name: policy-read
    namespace: default
  - kind: ServiceAccount
    name: policy-api-read
    namespace: default
  - kind: ServiceAccount
    name: policy-clamp-runtime-acm-read
    namespace: default
  - kind: ServiceAccount
    name: policy-pap-read
    namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io