spring:
  security:
    user:
      name: participantUser
      password: zb!XztG34
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.data.web.SpringDataWebAutoConfiguration
security:
  enable-csrf: false

dme:
  baseUrl: http://localhost:63475

participant:
  intermediaryParameters:
    reportingTimeIntervalMs: 120000
    description: Participant Description
    participantId: 101c62b3-8918-41b9-a747-d21eb79c6c08
    clampAutomationCompositionTopics:
      topicSources:
        - topic: policy-acruntime-participant
          servers:
            - ${topicServer:kafka.default.svc.cluster.local:9092}
          topicCommInfrastructure: NOOP
          fetchTimeout: 15000
      topicSinks:
        - topic: policy-acruntime-participant
          servers:
            - ${topicServer:kafka.default.svc.cluster.local:9092}
          topicCommInfrastructure: NOOP
    participantSupportedElementTypes:
      -
        typeName: org.onap.policy.clamp.acm.DMEAutomationCompositionElement
        typeVersion: 1.0.1

management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, metrics, prometheus
server:
  port: 8080
  servlet:
    context-path: /nonrtric/dmeparticipant
